version: '3.7'
services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/university
    expose:
      - 4000
    environment:
      - MIX_ENV=dev
    depends_on:
      - db
    networks:
      - webapp

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - webapp
    ports:
      - 5432:5432
    expose:
      - 5432

networks:
  webapp:
